cql( input heijden.pgn )

flipvertical
flipcolor

next (
		{square $pawn in P
		not p on up horizontal 1 $pawn
		not [Pp] on up $pawn}
		
		{square $pawn in P
		not p on up horizontal 1 $pawn
		not [Pp] on up $pawn}
		
		{square $pawn in P
		not p on up horizontal 1 $pawn
		not [Pp] on up $pawn}
		
		{square $pawn in P
		not p on up horizontal 1 $pawn
		not [Pp] on up $pawn}
		
		{square $pawn in P
		not p on up horizontal 1 $pawn
		not [Pp] on up $pawn}
		
		)
		
